package com.example.agriguard.modules.main.user.model.dto

data class IndemnityDto(
    var id: String? = null,
    var userId: String = "",
    var fillupdate: String = "",
    var dateOfBirth: String = "",
    var regular: Boolean = false,
    var punla: Boolean = false,
    var cooperativeRice: Boolean = false,
    var rsbsa: Boolean = false,
    var sikat: Boolean = false,
    var apcpc: Boolean = false,
    var others: String? = null,
    var causeOfDamage: String? = null,
    var dateOfLoss: String = "",
    var ageCultivation: String? = null,
    var areaDamaged: String? = null,
    var degreeOfDamage: String? = null,
    var expectedDateOfHarvest: String = "",
    var north: String? = null,
    var south: String? = null,
    var east: String? = null,
    var west: String? = null,
    var upaSaGawaBilang: String? = null,
    var upaSaGawaHalaga: String? = null,
    var binhiBilang: String? = null,
    var binhiHalaga: String? = null,
    var abonoBilang: String? = null,
    var abonoHalaga: String? = null,
    var kemikalBilang: String? = null,
    var kemikalHalaga: String? = null,
    var patubigBilang: String? = null,
    var patubigHalaga: String? = null,
    var ibapaBilang: String? = null,
    var ibapaHalaga: String? = null,
    var kabuuanBilang: String? = null,
    var kabuuanHalaga: String? = null,
    var createdById: String? = null,
    var createdAt: String? = null,
    var lastUpdatedById: String? = null,
    var lastUpdatedAt: String? = null,
    var deletedById: String? = null,
    var deletedAt: String? = null,
)
